- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - tmux
      - zsh
      - linuxbrew-wrapper
      - kubectl
      - python3
      - pip
